2023-08-29 07:05:13,903:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-08-29 07:05:13,903:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-08-29 07:05:13,903:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'your@email.com', '--agree-tos', '--no-eff-email', '-d', 'manual.itsmore.co.kr']
2023-08-29 07:05:13,903:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-08-29 07:05:14,211:DEBUG:certbot._internal.log:Root logging level set at 30
2023-08-29 07:05:14,220:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-08-29 07:05:14,222:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f71b463f6d0>
Prep: True
2023-08-29 07:05:14,224:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f71b463f6d0> and installer None
2023-08-29 07:05:14,225:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-08-29 07:05:14,285:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1280504436', new_authzr_uri=None, terms_of_service=None), 2c4dc6642af19e0bff77e981292528f6, Meta(creation_dt=datetime.datetime(2023, 8, 29, 5, 31, 58, tzinfo=<UTC>), creation_host='1224a63e3d80', register_to_eff=None))>
2023-08-29 07:05:14,287:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-08-29 07:05:14,289:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-08-29 07:05:14,841:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-08-29 07:05:14,842:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 29 Aug 2023 07:05:15 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "yJf7aswD4Ho": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2023-08-29 07:05:14,846:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for manual.itsmore.co.kr
2023-08-29 07:05:14,850:DEBUG:acme.client:Requesting fresh nonce
2023-08-29 07:05:14,851:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-08-29 07:05:15,022:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-08-29 07:05:15,023:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 29 Aug 2023 07:05:15 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: i3WdeBi2XT8ggqLRNhTo_7B_StUZyVPPZLWxymvjycbRcWWZqhw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-08-29 07:05:15,025:DEBUG:acme.client:Storing nonce: i3WdeBi2XT8ggqLRNhTo_7B_StUZyVPPZLWxymvjycbRcWWZqhw
2023-08-29 07:05:15,026:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "manual.itsmore.co.kr"\n    }\n  ]\n}'
2023-08-29 07:05:15,028:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI4MDUwNDQzNiIsICJub25jZSI6ICJpM1dkZUJpMlhUOGdncUxSTmhUb183Ql9TdFVaeVZQUFpMV3h5bXZqeWNiUmNXV1pxaHciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "TFhtZitO8E6SQARcUIGoUwh_a9pv7dd9YYn4HjOYWKKjs2kZlVSZIEJOQofMn3jA4mUmpWo-N-seAbzNc5Nmbtcs5QXLldJd5qLY7-Y2QaQ0MZhjZ2vd-YGtLmMmcx47WGPZP-f0PKaJds6vjiPHygIM4TxuBurBSCQilF5iqbCu7sSjbiynCsMAxxhX9ByvM4mPQ98YHRi9dZclv1mPfJnq_6QV09eXdR8wylV0a9PBxNj0PMDol26B7vlzA-SS3vdgr6SkKUd9v_WzqW3oLK86wyRkVT9IXJv31kE5s4Ea0NmAYKjczgso5lgf65gl_6xsjRdOSHZe7Lig_r1mYg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1hbnVhbC5pdHNtb3JlLmNvLmtyIgogICAgfQogIF0KfQ"
}
2023-08-29 07:05:15,215:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 213
2023-08-29 07:05:15,217:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Tue, 29 Aug 2023 07:05:15 GMT
Content-Type: application/problem+json
Content-Length: 213
Connection: keep-alive
Boulder-Requester: 1280504436
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Nr6fEcpOcoXcvbS1jJ4d6t5N-8CBnJXBfp6Vig4bFf0Iy7-DFqU

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2023-08-29 07:05:15,219:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 138, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 366, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 739, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 752, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 603, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2023-08-29 07:05:15,221:ERROR:certbot._internal.log:An unexpected error occurred:
2023-08-29 07:05:15,222:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
