2023-08-29 07:11:26,620:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-08-29 07:11:26,620:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-08-29 07:11:26,620:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'your@email.com', '--agree-tos', '--no-eff-email', '-d', 'manual.itsmore.co.kr']
2023-08-29 07:11:26,620:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-08-29 07:11:26,964:DEBUG:certbot._internal.log:Root logging level set at 30
2023-08-29 07:11:26,974:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-08-29 07:11:26,976:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fb76506b4f0>
Prep: True
2023-08-29 07:11:26,978:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fb76506b4f0> and installer None
2023-08-29 07:11:26,979:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-08-29 07:11:27,038:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1280504436', new_authzr_uri=None, terms_of_service=None), 2c4dc6642af19e0bff77e981292528f6, Meta(creation_dt=datetime.datetime(2023, 8, 29, 5, 31, 58, tzinfo=<UTC>), creation_host='1224a63e3d80', register_to_eff=None))>
2023-08-29 07:11:27,040:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-08-29 07:11:27,043:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-08-29 07:11:27,665:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-08-29 07:11:27,666:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 29 Aug 2023 07:11:28 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "GJ8igdZpiiI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-08-29 07:11:27,670:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for manual.itsmore.co.kr
2023-08-29 07:11:27,674:DEBUG:acme.client:Requesting fresh nonce
2023-08-29 07:11:27,675:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-08-29 07:11:27,869:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-08-29 07:11:27,870:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 29 Aug 2023 07:11:28 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 8GiKoOANhub2FB5Hq0iZYhccv8klK_RQFdWiPyfJkeATurzGdE4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-08-29 07:11:27,872:DEBUG:acme.client:Storing nonce: 8GiKoOANhub2FB5Hq0iZYhccv8klK_RQFdWiPyfJkeATurzGdE4
2023-08-29 07:11:27,873:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "manual.itsmore.co.kr"\n    }\n  ]\n}'
2023-08-29 07:11:27,876:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI4MDUwNDQzNiIsICJub25jZSI6ICI4R2lLb09BTmh1YjJGQjVIcTBpWlloY2N2OGtsS19SUUZkV2lQeWZKa2VBVHVyekdkRTQiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "Dhv7h9wQiZmyhNh7I9LQzYN-Q6U_zuBB5-3j5Ma8QFVigcnQ1FkCN9q0jfo4QKuy8Aqsz7Od_2CXclu9dJevGTRTVrZ_LQTGQb2Q2bWmSF1E3MG8qyPZmQyeZ_BIQWliDV8ptTr8ov2jT8qYTmB45LG3D_4rDKOh22xz8U5NjBEzsrnN5z_Apj3wGka2Pavkiwxfd6AFFwXiQPgjmn-9Am825wg7bIKomUX2NNSWXzp9uTQZQ333qt2kxNOl7AkLgB08FpAgS5RyWhlJvkURzeLebcQWeIOF06tOiwPpkmrAuacmFuZ4ZtOPLqpJICpoWfHvjU2QaJH9sHQZoAU9kg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1hbnVhbC5pdHNtb3JlLmNvLmtyIgogICAgfQogIF0KfQ"
}
2023-08-29 07:11:28,081:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 213
2023-08-29 07:11:28,083:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Tue, 29 Aug 2023 07:11:28 GMT
Content-Type: application/problem+json
Content-Length: 213
Connection: keep-alive
Boulder-Requester: 1280504436
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 8GiKoOANmznwip43eiZ94bwobJR4fvynzy23NypeM-smsAKrG7c

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2023-08-29 07:11:28,085:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 138, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 366, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 739, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 752, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 603, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2023-08-29 07:11:28,087:ERROR:certbot._internal.log:An unexpected error occurred:
2023-08-29 07:11:28,088:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
